// Code generated by cmd/gen/main.go. DO NOT EDIT.
package protocol

// ProtocolVersion identifies the Playwright spec version used to generate this file.
const ProtocolVersion = "main"

// Float returns a pointer to the given float64.
func Float(v float64) *float64 { return &v }

// Int returns a pointer to the given int.
func Int(v int) *int { return &v }

// String returns a pointer to the given string.
func String(v string) *string { return &v }

// Bool returns a pointer to the given bool.
func Bool(v bool) *bool { return &v }

type APIRequestContext struct {
	Guid string `json:"guid"`
}

type APIRequestContextDisposeRequest struct {
	Reason *string `json:"reason,omitempty"`
}

type APIRequestContextDisposeResponse struct {
}

type APIRequestContextDisposeAPIResponseRequest struct {
	FetchUid string `json:"fetchUid"`
}

type APIRequestContextDisposeAPIResponseResponse struct {
}

type APIRequestContextFetchRequest struct {
	EncodedParams     *string     `json:"encodedParams,omitempty"`
	FailOnStatusCode  *bool       `json:"failOnStatusCode,omitempty"`
	FormData          []NameValue `json:"formData"`
	Headers           []NameValue `json:"headers"`
	IgnoreHTTPSErrors *bool       `json:"ignoreHTTPSErrors,omitempty"`
	JsonData          *string     `json:"jsonData,omitempty"`
	MaxRedirects      *int        `json:"maxRedirects,omitempty"`
	MaxRetries        *int        `json:"maxRetries,omitempty"`
	Method            *string     `json:"method,omitempty"`
	MultipartData     []FormField `json:"multipartData"`
	Params            []NameValue `json:"params"`
	PostData          []byte      `json:"postData,omitempty"`
	Url               string      `json:"url"`
}

type APIRequestContextFetchResponse struct {
	Response APIResponse `json:"response"`
}

type APIRequestContextFetchLogRequest struct {
	FetchUid string `json:"fetchUid"`
}

type APIRequestContextFetchLogResponse struct {
	Log []string `json:"log"`
}

type APIRequestContextFetchResponseBodyRequest struct {
	FetchUid string `json:"fetchUid"`
}

type APIRequestContextFetchResponseBodyResponse struct {
	Binary []byte `json:"binary,omitempty"`
}

type APIRequestContextStorageStateRequest struct {
	IndexedDB *bool `json:"indexedDB,omitempty"`
}

type APIRequestContextStorageStateResponse struct {
	Cookies []NetworkCookie `json:"cookies"`
	Origins []OriginStorage `json:"origins"`
}

type APIResponse struct {
	FetchUid          string           `json:"fetchUid"`
	Headers           []NameValue      `json:"headers"`
	ResponseEndTiming *float64         `json:"responseEndTiming,omitempty"`
	SecurityDetails   *SecurityDetails `json:"securityDetails,omitempty"`
	ServerAddr        *RemoteAddr      `json:"serverAddr,omitempty"`
	Status            int              `json:"status"`
	StatusText        string           `json:"statusText"`
	Timing            *ResourceTiming  `json:"timing,omitempty"`
	Url               string           `json:"url"`
}

type Android struct {
	Guid string `json:"guid"`
}

type AndroidDevicesRequest struct {
	Host              *string `json:"host,omitempty"`
	OmitDriverInstall *bool   `json:"omitDriverInstall,omitempty"`
	Port              *int    `json:"port,omitempty"`
}

type AndroidDevicesResponse struct {
	Devices []AndroidDevice `json:"devices"`
}

type AndroidDevice struct {
	Guid string `json:"guid"`
}

type AndroidDeviceCloseRequest struct {
}

type AndroidDeviceCloseResponse struct {
}

type AndroidDeviceConnectToWebViewRequest struct {
	SocketName string `json:"socketName"`
}

type AndroidDeviceConnectToWebViewResponse struct {
	Context BrowserContext `json:"context"`
}

type AndroidDeviceDragRequest struct {
	AndroidSelector AndroidSelector `json:"androidSelector"`
	Dest            Point           `json:"dest"`
	Speed           *float64        `json:"speed,omitempty"`
}

type AndroidDeviceDragResponse struct {
}

type AndroidDeviceFillRequest struct {
	AndroidSelector AndroidSelector `json:"androidSelector"`
	Text            string          `json:"text"`
}

type AndroidDeviceFillResponse struct {
}

type AndroidDeviceFlingRequest struct {
	AndroidSelector AndroidSelector `json:"androidSelector"`
	Direction       any             `json:"direction"`
	Speed           *float64        `json:"speed,omitempty"`
}

type AndroidDeviceFlingResponse struct {
}

type AndroidDeviceInfoRequest struct {
	AndroidSelector AndroidSelector `json:"androidSelector"`
}

type AndroidDeviceInfoResponse struct {
	Info AndroidElementInfo `json:"info"`
}

type AndroidDeviceInputDragRequest struct {
	From  Point `json:"from"`
	Steps int   `json:"steps"`
	To    Point `json:"to"`
}

type AndroidDeviceInputDragResponse struct {
}

type AndroidDeviceInputPressRequest struct {
	Key string `json:"key"`
}

type AndroidDeviceInputPressResponse struct {
}

type AndroidDeviceInputSwipeRequest struct {
	Segments []Point `json:"segments"`
	Steps    int     `json:"steps"`
}

type AndroidDeviceInputSwipeResponse struct {
}

type AndroidDeviceInputTapRequest struct {
	Point Point `json:"point"`
}

type AndroidDeviceInputTapResponse struct {
}

type AndroidDeviceInputTypeRequest struct {
	Text string `json:"text"`
}

type AndroidDeviceInputTypeResponse struct {
}

type AndroidDeviceInstallApkRequest struct {
	Args []string `json:"args"`
	File []byte   `json:"file"`
}

type AndroidDeviceInstallApkResponse struct {
}

type AndroidDeviceLaunchBrowserRequest struct {
	Mixin any      `json:"$mixin"`
	Args  []string `json:"args"`
	Pkg   *string  `json:"pkg,omitempty"`
	Proxy any      `json:"proxy"`
}

type AndroidDeviceLaunchBrowserResponse struct {
	Context BrowserContext `json:"context"`
}

type AndroidDeviceLongTapRequest struct {
	AndroidSelector AndroidSelector `json:"androidSelector"`
}

type AndroidDeviceLongTapResponse struct {
}

type AndroidDeviceOpenRequest struct {
	Command string `json:"command"`
}

type AndroidDeviceOpenResponse struct {
	Socket AndroidSocket `json:"socket"`
}

type AndroidDevicePinchCloseRequest struct {
	AndroidSelector AndroidSelector `json:"androidSelector"`
	Percent         float64         `json:"percent"`
	Speed           *float64        `json:"speed,omitempty"`
}

type AndroidDevicePinchCloseResponse struct {
}

type AndroidDevicePinchOpenRequest struct {
	AndroidSelector AndroidSelector `json:"androidSelector"`
	Percent         float64         `json:"percent"`
	Speed           *float64        `json:"speed,omitempty"`
}

type AndroidDevicePinchOpenResponse struct {
}

type AndroidDevicePushRequest struct {
	File []byte `json:"file"`
	Mode *int   `json:"mode,omitempty"`
	Path string `json:"path"`
}

type AndroidDevicePushResponse struct {
}

type AndroidDeviceScreenshotRequest struct {
}

type AndroidDeviceScreenshotResponse struct {
	Binary []byte `json:"binary"`
}

type AndroidDeviceScrollRequest struct {
	AndroidSelector AndroidSelector `json:"androidSelector"`
	Direction       any             `json:"direction"`
	Percent         float64         `json:"percent"`
	Speed           *float64        `json:"speed,omitempty"`
}

type AndroidDeviceScrollResponse struct {
}

type AndroidDeviceShellRequest struct {
	Command string `json:"command"`
}

type AndroidDeviceShellResponse struct {
	Result []byte `json:"result"`
}

type AndroidDeviceSwipeRequest struct {
	AndroidSelector AndroidSelector `json:"androidSelector"`
	Direction       any             `json:"direction"`
	Percent         float64         `json:"percent"`
	Speed           *float64        `json:"speed,omitempty"`
}

type AndroidDeviceSwipeResponse struct {
}

type AndroidDeviceTapRequest struct {
	AndroidSelector AndroidSelector `json:"androidSelector"`
	Duration        *float64        `json:"duration,omitempty"`
}

type AndroidDeviceTapResponse struct {
}

type AndroidDeviceWaitRequest struct {
	AndroidSelector AndroidSelector `json:"androidSelector"`
	State           any             `json:"state"`
}

type AndroidDeviceWaitResponse struct {
}

type AndroidDeviceCloseEvent struct {
}

type AndroidDeviceWebViewAddedEvent struct {
	WebView AndroidWebView `json:"webView"`
}

type AndroidDeviceWebViewRemovedEvent struct {
	SocketName string `json:"socketName"`
}

type AndroidElementInfo struct {
	Bounds        Rect                 `json:"bounds"`
	Checkable     bool                 `json:"checkable"`
	Checked       bool                 `json:"checked"`
	Children      []AndroidElementInfo `json:"children"`
	Clazz         string               `json:"clazz"`
	Clickable     bool                 `json:"clickable"`
	Desc          string               `json:"desc"`
	Enabled       bool                 `json:"enabled"`
	Focusable     bool                 `json:"focusable"`
	Focused       bool                 `json:"focused"`
	LongClickable bool                 `json:"longClickable"`
	Pkg           string               `json:"pkg"`
	Res           string               `json:"res"`
	Scrollable    bool                 `json:"scrollable"`
	Selected      bool                 `json:"selected"`
	Text          string               `json:"text"`
}

type AndroidSelector struct {
	Checkable     *bool   `json:"checkable,omitempty"`
	Checked       *bool   `json:"checked,omitempty"`
	Clazz         *string `json:"clazz,omitempty"`
	Clickable     *bool   `json:"clickable,omitempty"`
	Depth         *int    `json:"depth,omitempty"`
	Desc          *string `json:"desc,omitempty"`
	Enabled       *bool   `json:"enabled,omitempty"`
	Focusable     *bool   `json:"focusable,omitempty"`
	Focused       *bool   `json:"focused,omitempty"`
	HasChild      any     `json:"hasChild"`
	HasDescendant any     `json:"hasDescendant"`
	LongClickable *bool   `json:"longClickable,omitempty"`
	Pkg           *string `json:"pkg,omitempty"`
	Res           *string `json:"res,omitempty"`
	Scrollable    *bool   `json:"scrollable,omitempty"`
	Selected      *bool   `json:"selected,omitempty"`
	Text          *string `json:"text,omitempty"`
}

type AndroidSocket struct {
	Guid string `json:"guid"`
}

type AndroidSocketCloseRequest struct {
}

type AndroidSocketCloseResponse struct {
}

type AndroidSocketWriteRequest struct {
	Data []byte `json:"data"`
}

type AndroidSocketWriteResponse struct {
}

type AndroidSocketCloseEvent struct {
}

type AndroidSocketDataEvent struct {
	Data []byte `json:"data"`
}

type AndroidWebView struct {
	Pid        int    `json:"pid"`
	Pkg        string `json:"pkg"`
	SocketName string `json:"socketName"`
}

type Artifact struct {
	Guid string `json:"guid"`
}

type ArtifactCancelRequest struct {
}

type ArtifactCancelResponse struct {
}

type ArtifactDeleteRequest struct {
}

type ArtifactDeleteResponse struct {
}

type ArtifactFailureRequest struct {
}

type ArtifactFailureResponse struct {
	Error *string `json:"error,omitempty"`
}

type ArtifactPathAfterFinishedRequest struct {
}

type ArtifactPathAfterFinishedResponse struct {
	Value string `json:"value"`
}

type ArtifactSaveAsRequest struct {
	Path string `json:"path"`
}

type ArtifactSaveAsResponse struct {
}

type ArtifactSaveAsStreamRequest struct {
}

type ArtifactSaveAsStreamResponse struct {
	Stream Stream `json:"stream"`
}

type ArtifactStreamRequest struct {
}

type ArtifactStreamResponse struct {
	Stream Stream `json:"stream"`
}

type BindingCall struct {
	Guid string `json:"guid"`
}

type BindingCallRejectRequest struct {
	Error SerializedError `json:"error"`
}

type BindingCallRejectResponse struct {
}

type BindingCallResolveRequest struct {
	Result SerializedArgument `json:"result"`
}

type BindingCallResolveResponse struct {
}

type Browser struct {
	Guid string `json:"guid"`
}

type BrowserCloseRequest struct {
	Reason *string `json:"reason,omitempty"`
}

type BrowserCloseResponse struct {
}

type BrowserDefaultUserAgentForTestRequest struct {
}

type BrowserDefaultUserAgentForTestResponse struct {
	UserAgent string `json:"userAgent"`
}

type BrowserDisconnectFromReusedContextRequest struct {
	Reason string `json:"reason"`
}

type BrowserDisconnectFromReusedContextResponse struct {
}

type BrowserKillForTestsRequest struct {
}

type BrowserKillForTestsResponse struct {
}

type BrowserNewBrowserCDPSessionRequest struct {
}

type BrowserNewBrowserCDPSessionResponse struct {
	Session CDPSession `json:"session"`
}

type BrowserNewContextRequest struct {
	Mixin        any `json:"$mixin"`
	Proxy        any `json:"proxy"`
	StorageState any `json:"storageState"`
}

type BrowserNewContextResponse struct {
	Context BrowserContext `json:"context"`
}

type BrowserNewContextForReuseRequest struct {
	Mixin        any `json:"$mixin"`
	Proxy        any `json:"proxy"`
	StorageState any `json:"storageState"`
}

type BrowserNewContextForReuseResponse struct {
	Context BrowserContext `json:"context"`
}

type BrowserStartServerRequest struct {
	Host         *string `json:"host,omitempty"`
	Metadata     any     `json:"metadata,omitempty"`
	Port         *int    `json:"port,omitempty"`
	Title        string  `json:"title"`
	WorkspaceDir *string `json:"workspaceDir,omitempty"`
}

type BrowserStartServerResponse struct {
	Endpoint string `json:"endpoint"`
}

type BrowserStartTracingRequest struct {
	Categories  []string `json:"categories"`
	Page        *Page    `json:"page,omitempty"`
	Screenshots *bool    `json:"screenshots,omitempty"`
}

type BrowserStartTracingResponse struct {
}

type BrowserStopServerRequest struct {
}

type BrowserStopServerResponse struct {
}

type BrowserStopTracingRequest struct {
}

type BrowserStopTracingResponse struct {
	Artifact Artifact `json:"artifact"`
}

type BrowserCloseEvent struct {
}

type BrowserContextEvent struct {
	Context BrowserContext `json:"context"`
}

type BrowserContext struct {
	Guid string `json:"guid"`
}

type BrowserContextAddCookiesRequest struct {
	Cookies []SetNetworkCookie `json:"cookies"`
}

type BrowserContextAddCookiesResponse struct {
}

type BrowserContextAddInitScriptRequest struct {
	Source string `json:"source"`
}

type BrowserContextAddInitScriptResponse struct {
	Disposable Disposable `json:"disposable"`
}

type BrowserContextClearCookiesRequest struct {
	Domain            *string `json:"domain,omitempty"`
	DomainRegexFlags  *string `json:"domainRegexFlags,omitempty"`
	DomainRegexSource *string `json:"domainRegexSource,omitempty"`
	Name              *string `json:"name,omitempty"`
	NameRegexFlags    *string `json:"nameRegexFlags,omitempty"`
	NameRegexSource   *string `json:"nameRegexSource,omitempty"`
	Path              *string `json:"path,omitempty"`
	PathRegexFlags    *string `json:"pathRegexFlags,omitempty"`
	PathRegexSource   *string `json:"pathRegexSource,omitempty"`
}

type BrowserContextClearCookiesResponse struct {
}

type BrowserContextClearPermissionsRequest struct {
}

type BrowserContextClearPermissionsResponse struct {
}

type BrowserContextClockFastForwardRequest struct {
	TicksNumber *float64 `json:"ticksNumber,omitempty"`
	TicksString *string  `json:"ticksString,omitempty"`
}

type BrowserContextClockFastForwardResponse struct {
}

type BrowserContextClockInstallRequest struct {
	TimeNumber *float64 `json:"timeNumber,omitempty"`
	TimeString *string  `json:"timeString,omitempty"`
}

type BrowserContextClockInstallResponse struct {
}

type BrowserContextClockPauseAtRequest struct {
	TimeNumber *float64 `json:"timeNumber,omitempty"`
	TimeString *string  `json:"timeString,omitempty"`
}

type BrowserContextClockPauseAtResponse struct {
}

type BrowserContextClockResumeRequest struct {
}

type BrowserContextClockResumeResponse struct {
}

type BrowserContextClockRunForRequest struct {
	TicksNumber *float64 `json:"ticksNumber,omitempty"`
	TicksString *string  `json:"ticksString,omitempty"`
}

type BrowserContextClockRunForResponse struct {
}

type BrowserContextClockSetFixedTimeRequest struct {
	TimeNumber *float64 `json:"timeNumber,omitempty"`
	TimeString *string  `json:"timeString,omitempty"`
}

type BrowserContextClockSetFixedTimeResponse struct {
}

type BrowserContextClockSetSystemTimeRequest struct {
	TimeNumber *float64 `json:"timeNumber,omitempty"`
	TimeString *string  `json:"timeString,omitempty"`
}

type BrowserContextClockSetSystemTimeResponse struct {
}

type BrowserContextCloseRequest struct {
	Reason *string `json:"reason,omitempty"`
}

type BrowserContextCloseResponse struct {
}

type BrowserContextCookiesRequest struct {
	Urls []string `json:"urls"`
}

type BrowserContextCookiesResponse struct {
	Cookies []NetworkCookie `json:"cookies"`
}

type BrowserContextCreateTempFilesRequest struct {
	Items       []any   `json:"items"`
	RootDirName *string `json:"rootDirName,omitempty"`
}

type BrowserContextCreateTempFilesResponse struct {
	RootDir         *WritableStream  `json:"rootDir,omitempty"`
	WritableStreams []WritableStream `json:"writableStreams"`
}

type BrowserContextCredentialsCreateRequest struct {
	Id         *string `json:"id,omitempty"`
	PrivateKey *string `json:"privateKey,omitempty"`
	PublicKey  *string `json:"publicKey,omitempty"`
	RpId       string  `json:"rpId"`
	UserHandle *string `json:"userHandle,omitempty"`
}

type BrowserContextCredentialsCreateResponse struct {
	Credential VirtualCredential `json:"credential"`
}

type BrowserContextCredentialsDeleteRequest struct {
	Id string `json:"id"`
}

type BrowserContextCredentialsDeleteResponse struct {
}

type BrowserContextCredentialsGetRequest struct {
	Id   *string `json:"id,omitempty"`
	RpId *string `json:"rpId,omitempty"`
}

type BrowserContextCredentialsGetResponse struct {
	Credentials []VirtualCredential `json:"credentials"`
}

type BrowserContextCredentialsInstallRequest struct {
}

type BrowserContextCredentialsInstallResponse struct {
}

type BrowserContextDisableRecorderRequest struct {
}

type BrowserContextDisableRecorderResponse struct {
}

type BrowserContextEnableRecorderRequest struct {
	ContextOptions       any     `json:"contextOptions,omitempty"`
	Device               *string `json:"device,omitempty"`
	HandleSIGINT         *bool   `json:"handleSIGINT,omitempty"`
	Language             *string `json:"language,omitempty"`
	LaunchOptions        any     `json:"launchOptions,omitempty"`
	Mode                 any     `json:"mode"`
	OmitCallTracking     *bool   `json:"omitCallTracking,omitempty"`
	OutputFile           *string `json:"outputFile,omitempty"`
	PauseOnNextStatement *bool   `json:"pauseOnNextStatement,omitempty"`
	RecorderMode         any     `json:"recorderMode"`
	SaveStorage          *string `json:"saveStorage,omitempty"`
	TestIdAttributeName  *string `json:"testIdAttributeName,omitempty"`
}

type BrowserContextEnableRecorderResponse struct {
}

type BrowserContextExposeBindingRequest struct {
	Name     string `json:"name"`
	NoGlobal *bool  `json:"noGlobal,omitempty"`
}

type BrowserContextExposeBindingResponse struct {
	Disposable Disposable `json:"disposable"`
}

type BrowserContextExposeConsoleApiRequest struct {
}

type BrowserContextExposeConsoleApiResponse struct {
}

type BrowserContextGrantPermissionsRequest struct {
	Origin      *string  `json:"origin,omitempty"`
	Permissions []string `json:"permissions"`
}

type BrowserContextGrantPermissionsResponse struct {
}

type BrowserContextNewCDPSessionRequest struct {
	Frame *Frame `json:"frame,omitempty"`
	Page  *Page  `json:"page,omitempty"`
}

type BrowserContextNewCDPSessionResponse struct {
	Session CDPSession `json:"session"`
}

type BrowserContextNewPageRequest struct {
}

type BrowserContextNewPageResponse struct {
	Page Page `json:"page"`
}

type BrowserContextPauseRequest struct {
}

type BrowserContextPauseResponse struct {
}

type BrowserContextRegisterSelectorEngineRequest struct {
	SelectorEngine SelectorEngine `json:"selectorEngine"`
}

type BrowserContextRegisterSelectorEngineResponse struct {
}

type BrowserContextSetExtraHTTPHeadersRequest struct {
	Headers []NameValue `json:"headers"`
}

type BrowserContextSetExtraHTTPHeadersResponse struct {
}

type BrowserContextSetGeolocationRequest struct {
	Geolocation any `json:"geolocation"`
}

type BrowserContextSetGeolocationResponse struct {
}

type BrowserContextSetHTTPCredentialsRequest struct {
	HttpCredentials []HttpCredentials `json:"httpCredentials"`
}

type BrowserContextSetHTTPCredentialsResponse struct {
}

type BrowserContextSetNetworkInterceptionPatternsRequest struct {
	Patterns []any `json:"patterns"`
}

type BrowserContextSetNetworkInterceptionPatternsResponse struct {
}

type BrowserContextSetOfflineRequest struct {
	Offline bool `json:"offline"`
}

type BrowserContextSetOfflineResponse struct {
}

type BrowserContextSetStorageStateRequest struct {
	StorageState any `json:"storageState"`
}

type BrowserContextSetStorageStateResponse struct {
}

type BrowserContextSetTestIdAttributeNameRequest struct {
	TestIdAttributeName string `json:"testIdAttributeName"`
}

type BrowserContextSetTestIdAttributeNameResponse struct {
}

type BrowserContextSetWebSocketInterceptionPatternsRequest struct {
	Patterns []any `json:"patterns"`
}

type BrowserContextSetWebSocketInterceptionPatternsResponse struct {
}

type BrowserContextStorageStateRequest struct {
	Credentials *bool `json:"credentials,omitempty"`
	IndexedDB   *bool `json:"indexedDB,omitempty"`
}

type BrowserContextStorageStateResponse struct {
	Cookies     []NetworkCookie     `json:"cookies"`
	Credentials []VirtualCredential `json:"credentials"`
	Origins     []OriginStorage     `json:"origins"`
}

type BrowserContextUpdateSubscriptionRequest struct {
	Enabled bool `json:"enabled"`
	Event   any  `json:"event"`
}

type BrowserContextUpdateSubscriptionResponse struct {
}

type BrowserContextBindingCallEvent struct {
	Binding BindingCall `json:"binding"`
}

type BrowserContextCloseEvent struct {
}

type BrowserContextConsoleEvent struct {
	Mixin  any     `json:"$mixin"`
	Page   *Page   `json:"page,omitempty"`
	Worker *Worker `json:"worker,omitempty"`
}

type BrowserContextDialogEvent struct {
	Dialog Dialog `json:"dialog"`
}

type BrowserContextDialogClosedEvent struct {
	Dialog Dialog `json:"dialog"`
}

type BrowserContextPageEvent struct {
	Page Page `json:"page"`
}

type BrowserContextPageErrorEvent struct {
	Error    SerializedError `json:"error"`
	Location any             `json:"location"`
	Page     Page            `json:"page"`
}

type BrowserContextRecorderEventEvent struct {
	Code  string `json:"code"`
	Data  any    `json:"data"`
	Event any    `json:"event"`
	Page  Page   `json:"page"`
}

type BrowserContextRequestEvent struct {
	Page    *Page   `json:"page,omitempty"`
	Request Request `json:"request"`
}

type BrowserContextRequestFailedEvent struct {
	FailureText       *string `json:"failureText,omitempty"`
	Page              *Page   `json:"page,omitempty"`
	Request           Request `json:"request"`
	ResponseEndTiming float64 `json:"responseEndTiming"`
}

type BrowserContextRequestFinishedEvent struct {
	Page              *Page     `json:"page,omitempty"`
	Request           Request   `json:"request"`
	Response          *Response `json:"response,omitempty"`
	ResponseEndTiming float64   `json:"responseEndTiming"`
}

type BrowserContextResponseEvent struct {
	Page     *Page    `json:"page,omitempty"`
	Response Response `json:"response"`
}

type BrowserContextRouteEvent struct {
	Route Route `json:"route"`
}

type BrowserContextServiceWorkerEvent struct {
	Worker Worker `json:"worker"`
}

type BrowserContextWebSocketRouteEvent struct {
	WebSocketRoute WebSocketRoute `json:"webSocketRoute"`
}

type BrowserType struct {
	Guid string `json:"guid"`
}

type BrowserTypeConnectOverCDPRequest struct {
	ArtifactsDir *string     `json:"artifactsDir,omitempty"`
	EndpointURL  *string     `json:"endpointURL,omitempty"`
	Headers      []NameValue `json:"headers"`
	IsLocal      *bool       `json:"isLocal,omitempty"`
	NoDefaults   *bool       `json:"noDefaults,omitempty"`
	SlowMo       *float64    `json:"slowMo,omitempty"`
	Transport    []byte      `json:"transport,omitempty"`
}

type BrowserTypeConnectOverCDPResponse struct {
	Browser        Browser         `json:"browser"`
	DefaultContext *BrowserContext `json:"defaultContext,omitempty"`
}

type BrowserTypeConnectToWorkerRequest struct {
	Endpoint string `json:"endpoint"`
}

type BrowserTypeConnectToWorkerResponse struct {
	Worker Worker `json:"worker"`
}

type BrowserTypeLaunchRequest struct {
	Mixin  any      `json:"$mixin"`
	SlowMo *float64 `json:"slowMo,omitempty"`
}

type BrowserTypeLaunchResponse struct {
	Browser Browser `json:"browser"`
}

type BrowserTypeLaunchPersistentContextRequest struct {
	Mixin1      any      `json:"$mixin1"`
	Mixin2      any      `json:"$mixin2"`
	SlowMo      *float64 `json:"slowMo,omitempty"`
	UserDataDir string   `json:"userDataDir"`
}

type BrowserTypeLaunchPersistentContextResponse struct {
	Browser Browser        `json:"browser"`
	Context BrowserContext `json:"context"`
}

type CDPSession struct {
	Guid string `json:"guid"`
}

type CDPSessionDetachRequest struct {
}

type CDPSessionDetachResponse struct {
}

type CDPSessionSendRequest struct {
	Method string `json:"method"`
	Params any    `json:"params,omitempty"`
}

type CDPSessionSendResponse struct {
	Result any `json:"result"`
}

type CDPSessionCloseEvent struct {
}

type CDPSessionEventEvent struct {
	Method string `json:"method"`
	Params any    `json:"params,omitempty"`
}

type ClientSideCallMetadata struct {
	Id    int          `json:"id"`
	Stack []StackFrame `json:"stack"`
}

type ConsoleMessagesFilter string

const (
	ConsoleMessagesFilterAll             ConsoleMessagesFilter = "all"
	ConsoleMessagesFilterSincenavigation ConsoleMessagesFilter = "since-navigation"
)

type DebugController struct {
	Guid string `json:"guid"`
}

type DebugControllerHideHighlightRequest struct {
}

type DebugControllerHideHighlightResponse struct {
}

type DebugControllerHighlightRequest struct {
	AriaTemplate *string `json:"ariaTemplate,omitempty"`
	Selector     *string `json:"selector,omitempty"`
}

type DebugControllerHighlightResponse struct {
}

type DebugControllerInitializeRequest struct {
	CodegenId   string      `json:"codegenId"`
	SdkLanguage SDKLanguage `json:"sdkLanguage"`
}

type DebugControllerInitializeResponse struct {
}

type DebugControllerKillRequest struct {
}

type DebugControllerKillResponse struct {
}

type DebugControllerResumeRequest struct {
}

type DebugControllerResumeResponse struct {
}

type DebugControllerSetRecorderModeRequest struct {
	GenerateAutoExpect  *bool   `json:"generateAutoExpect,omitempty"`
	Mode                any     `json:"mode"`
	TestIdAttributeName *string `json:"testIdAttributeName,omitempty"`
}

type DebugControllerSetRecorderModeResponse struct {
}

type DebugControllerSetReportStateChangedRequest struct {
	Enabled bool `json:"enabled"`
}

type DebugControllerSetReportStateChangedResponse struct {
}

type DebugControllerInspectRequestedEvent struct {
	AriaSnapshot string `json:"ariaSnapshot"`
	Locator      string `json:"locator"`
	Selector     string `json:"selector"`
}

type DebugControllerPausedEvent struct {
	Paused bool `json:"paused"`
}

type DebugControllerSetModeRequestedEvent struct {
	Mode string `json:"mode"`
}

type DebugControllerSourceChangedEvent struct {
	Actions []string `json:"actions"`
	Footer  *string  `json:"footer,omitempty"`
	Header  *string  `json:"header,omitempty"`
	Text    string   `json:"text"`
}

type DebugControllerStateChangedEvent struct {
	PageCount int `json:"pageCount"`
}

type Debugger struct {
	Guid string `json:"guid"`
}

type DebuggerEnableRequest struct {
}

type DebuggerEnableResponse struct {
}

type DebuggerNextRequest struct {
}

type DebuggerNextResponse struct {
}

type DebuggerRequestPauseRequest struct {
}

type DebuggerRequestPauseResponse struct {
}

type DebuggerResumeRequest struct {
}

type DebuggerResumeResponse struct {
}

type DebuggerRunToRequest struct {
	Location any `json:"location"`
}

type DebuggerRunToResponse struct {
}

type DebuggerApiCallsUpdatedEvent struct {
	ApiCalls []any `json:"apiCalls"`
}

type DebuggerPausedStateChangedEvent struct {
	PausedDetails any `json:"pausedDetails"`
}

type Dialog struct {
	Guid string `json:"guid"`
}

type DialogAcceptRequest struct {
	PromptText *string `json:"promptText,omitempty"`
}

type DialogAcceptResponse struct {
}

type DialogDismissRequest struct {
}

type DialogDismissResponse struct {
}

type Disposable struct {
	Guid string `json:"guid"`
}

type DisposableDisposeRequest struct {
}

type DisposableDisposeResponse struct {
}

type Electron struct {
	Guid string `json:"guid"`
}

type ElectronLaunchRequest struct {
	AcceptDownloads     any               `json:"acceptDownloads"`
	Args                []string          `json:"args"`
	ArtifactsDir        *string           `json:"artifactsDir,omitempty"`
	BypassCSP           *bool             `json:"bypassCSP,omitempty"`
	ChromiumSandbox     *bool             `json:"chromiumSandbox,omitempty"`
	ColorScheme         any               `json:"colorScheme"`
	Cwd                 *string           `json:"cwd,omitempty"`
	Env                 []NameValue       `json:"env"`
	ExecutablePath      *string           `json:"executablePath,omitempty"`
	ExtraHTTPHeaders    []NameValue       `json:"extraHTTPHeaders"`
	Geolocation         any               `json:"geolocation"`
	HttpCredentials     []HttpCredentials `json:"httpCredentials"`
	IgnoreHTTPSErrors   *bool             `json:"ignoreHTTPSErrors,omitempty"`
	Locale              *string           `json:"locale,omitempty"`
	Offline             *bool             `json:"offline,omitempty"`
	PierceFrames        *bool             `json:"pierceFrames,omitempty"`
	RecordVideo         any               `json:"recordVideo"`
	SelectorEngines     []SelectorEngine  `json:"selectorEngines"`
	StrictSelectors     *bool             `json:"strictSelectors,omitempty"`
	TestIdAttributeName *string           `json:"testIdAttributeName,omitempty"`
	TimezoneId          *string           `json:"timezoneId,omitempty"`
	TracesDir           *string           `json:"tracesDir,omitempty"`
}

type ElectronLaunchResponse struct {
	ElectronApplication ElectronApplication `json:"electronApplication"`
}

type ElectronApplication struct {
	Guid string `json:"guid"`
}

type ElectronApplicationBrowserWindowRequest struct {
	Page Page `json:"page"`
}

type ElectronApplicationBrowserWindowResponse struct {
	Handle JSHandle `json:"handle"`
}

type ElectronApplicationEvaluateExpressionRequest struct {
	Arg        SerializedArgument `json:"arg"`
	Expression string             `json:"expression"`
	IsFunction *bool              `json:"isFunction,omitempty"`
}

type ElectronApplicationEvaluateExpressionResponse struct {
	Value SerializedValue `json:"value"`
}

type ElectronApplicationEvaluateExpressionHandleRequest struct {
	Arg        SerializedArgument `json:"arg"`
	Expression string             `json:"expression"`
	IsFunction *bool              `json:"isFunction,omitempty"`
}

type ElectronApplicationEvaluateExpressionHandleResponse struct {
	Handle JSHandle `json:"handle"`
}

type ElectronApplicationUpdateSubscriptionRequest struct {
	Enabled bool `json:"enabled"`
	Event   any  `json:"event"`
}

type ElectronApplicationUpdateSubscriptionResponse struct {
}

type ElectronApplicationCloseEvent struct {
}

type ElectronApplicationConsoleEvent struct {
	Mixin any `json:"$mixin"`
}

type ElementHandle struct {
	Guid string `json:"guid"`
}

type ElementHandleBoundingBoxRequest struct {
}

type ElementHandleBoundingBoxResponse struct {
	Value *Rect `json:"value,omitempty"`
}

type ElementHandleCheckRequest struct {
	Force    *bool  `json:"force,omitempty"`
	Position *Point `json:"position,omitempty"`
	Scroll   any    `json:"scroll"`
	Trial    *bool  `json:"trial,omitempty"`
}

type ElementHandleCheckResponse struct {
}

type ElementHandleClickRequest struct {
	Button      any      `json:"button"`
	ClickCount  *int     `json:"clickCount,omitempty"`
	Delay       *float64 `json:"delay,omitempty"`
	Force       *bool    `json:"force,omitempty"`
	Modifiers   []any    `json:"modifiers"`
	NoWaitAfter *bool    `json:"noWaitAfter,omitempty"`
	Position    *Point   `json:"position,omitempty"`
	Scroll      any      `json:"scroll"`
	Steps       *int     `json:"steps,omitempty"`
	Trial       *bool    `json:"trial,omitempty"`
}

type ElementHandleClickResponse struct {
}

type ElementHandleContentFrameRequest struct {
}

type ElementHandleContentFrameResponse struct {
	Frame *Frame `json:"frame,omitempty"`
}

type ElementHandleDblclickRequest struct {
	Button    any      `json:"button"`
	Delay     *float64 `json:"delay,omitempty"`
	Force     *bool    `json:"force,omitempty"`
	Modifiers []any    `json:"modifiers"`
	Position  *Point   `json:"position,omitempty"`
	Scroll    any      `json:"scroll"`
	Steps     *int     `json:"steps,omitempty"`
	Trial     *bool    `json:"trial,omitempty"`
}

type ElementHandleDblclickResponse struct {
}

type ElementHandleDispatchEventRequest struct {
	EventInit SerializedArgument `json:"eventInit"`
	Type      string             `json:"type"`
}

type ElementHandleDispatchEventResponse struct {
}

type ElementHandleEvalOnSelectorRequest struct {
	Arg        SerializedArgument `json:"arg"`
	Expression string             `json:"expression"`
	IsFunction *bool              `json:"isFunction,omitempty"`
	Selector   string             `json:"selector"`
	Strict     *bool              `json:"strict,omitempty"`
}

type ElementHandleEvalOnSelectorResponse struct {
	Value SerializedValue `json:"value"`
}

type ElementHandleEvalOnSelectorAllRequest struct {
	Arg        SerializedArgument `json:"arg"`
	Expression string             `json:"expression"`
	IsFunction *bool              `json:"isFunction,omitempty"`
	Selector   string             `json:"selector"`
}

type ElementHandleEvalOnSelectorAllResponse struct {
	Value SerializedValue `json:"value"`
}

type ElementHandleFillRequest struct {
	Force *bool  `json:"force,omitempty"`
	Value string `json:"value"`
}

type ElementHandleFillResponse struct {
}

type ElementHandleFocusRequest struct {
}

type ElementHandleFocusResponse struct {
}

type ElementHandleGetAttributeRequest struct {
	Name string `json:"name"`
}

type ElementHandleGetAttributeResponse struct {
	Value *string `json:"value,omitempty"`
}

type ElementHandleHoverRequest struct {
	Force     *bool  `json:"force,omitempty"`
	Modifiers []any  `json:"modifiers"`
	Position  *Point `json:"position,omitempty"`
	Scroll    any    `json:"scroll"`
	Trial     *bool  `json:"trial,omitempty"`
}

type ElementHandleHoverResponse struct {
}

type ElementHandleInnerHTMLRequest struct {
}

type ElementHandleInnerHTMLResponse struct {
	Value string `json:"value"`
}

type ElementHandleInnerTextRequest struct {
}

type ElementHandleInnerTextResponse struct {
	Value string `json:"value"`
}

type ElementHandleInputValueRequest struct {
}

type ElementHandleInputValueResponse struct {
	Value string `json:"value"`
}

type ElementHandleIsCheckedRequest struct {
}

type ElementHandleIsCheckedResponse struct {
	Value bool `json:"value"`
}

type ElementHandleIsDisabledRequest struct {
}

type ElementHandleIsDisabledResponse struct {
	Value bool `json:"value"`
}

type ElementHandleIsEditableRequest struct {
}

type ElementHandleIsEditableResponse struct {
	Value bool `json:"value"`
}

type ElementHandleIsEnabledRequest struct {
}

type ElementHandleIsEnabledResponse struct {
	Value bool `json:"value"`
}

type ElementHandleIsHiddenRequest struct {
}

type ElementHandleIsHiddenResponse struct {
	Value bool `json:"value"`
}

type ElementHandleIsVisibleRequest struct {
}

type ElementHandleIsVisibleResponse struct {
	Value bool `json:"value"`
}

type ElementHandleOwnerFrameRequest struct {
}

type ElementHandleOwnerFrameResponse struct {
	Frame *Frame `json:"frame,omitempty"`
}

type ElementHandlePressRequest struct {
	Delay       *float64 `json:"delay,omitempty"`
	Key         string   `json:"key"`
	NoWaitAfter *bool    `json:"noWaitAfter,omitempty"`
}

type ElementHandlePressResponse struct {
}

type ElementHandleQuerySelectorRequest struct {
	Selector string `json:"selector"`
	Strict   *bool  `json:"strict,omitempty"`
}

type ElementHandleQuerySelectorResponse struct {
	Element *ElementHandle `json:"element,omitempty"`
}

type ElementHandleQuerySelectorAllRequest struct {
	Selector string `json:"selector"`
}

type ElementHandleQuerySelectorAllResponse struct {
	Elements []ElementHandle `json:"elements"`
}

type ElementHandleScreenshotRequest struct {
	Mixin   any  `json:"$mixin"`
	Quality *int `json:"quality,omitempty"`
	Type    any  `json:"type"`
}

type ElementHandleScreenshotResponse struct {
	Binary []byte `json:"binary"`
}

type ElementHandleScrollIntoViewIfNeededRequest struct {
}

type ElementHandleScrollIntoViewIfNeededResponse struct {
}

type ElementHandleSelectOptionRequest struct {
	Elements []ElementHandle `json:"elements"`
	Force    *bool           `json:"force,omitempty"`
	Options  []any           `json:"options"`
}

type ElementHandleSelectOptionResponse struct {
	Values []string `json:"values"`
}

type ElementHandleSelectTextRequest struct {
	Force *bool `json:"force,omitempty"`
}

type ElementHandleSelectTextResponse struct {
}

type ElementHandleSetInputFilesRequest struct {
	DirectoryStream *WritableStream  `json:"directoryStream,omitempty"`
	LocalDirectory  *string          `json:"localDirectory,omitempty"`
	LocalPaths      []string         `json:"localPaths"`
	Payloads        []any            `json:"payloads"`
	Streams         []WritableStream `json:"streams"`
}

type ElementHandleSetInputFilesResponse struct {
}

type ElementHandleTapRequest struct {
	Force     *bool  `json:"force,omitempty"`
	Modifiers []any  `json:"modifiers"`
	Position  *Point `json:"position,omitempty"`
	Scroll    any    `json:"scroll"`
	Trial     *bool  `json:"trial,omitempty"`
}

type ElementHandleTapResponse struct {
}

type ElementHandleTextContentRequest struct {
}

type ElementHandleTextContentResponse struct {
	Value *string `json:"value,omitempty"`
}

type ElementHandleTypeRequest struct {
	Delay *float64 `json:"delay,omitempty"`
	Text  string   `json:"text"`
}

type ElementHandleTypeResponse struct {
}

type ElementHandleUncheckRequest struct {
	Force    *bool  `json:"force,omitempty"`
	Position *Point `json:"position,omitempty"`
	Scroll   any    `json:"scroll"`
	Trial    *bool  `json:"trial,omitempty"`
}

type ElementHandleUncheckResponse struct {
}

type ElementHandleWaitForElementStateRequest struct {
	State any `json:"state"`
}

type ElementHandleWaitForElementStateResponse struct {
}

type ElementHandleWaitForSelectorRequest struct {
	Selector string `json:"selector"`
	State    any    `json:"state"`
	Strict   *bool  `json:"strict,omitempty"`
}

type ElementHandleWaitForSelectorResponse struct {
	Element *ElementHandle `json:"element,omitempty"`
}

type ExpectedTextValue struct {
	IgnoreCase          *bool   `json:"ignoreCase,omitempty"`
	MatchSubstring      *bool   `json:"matchSubstring,omitempty"`
	NormalizeWhiteSpace *bool   `json:"normalizeWhiteSpace,omitempty"`
	RegexFlags          *string `json:"regexFlags,omitempty"`
	RegexSource         *string `json:"regexSource,omitempty"`
	String              *string `json:"string,omitempty"`
}

type FormField struct {
	File  any     `json:"file"`
	Name  string  `json:"name"`
	Value *string `json:"value,omitempty"`
}

type Frame struct {
	Guid string `json:"guid"`
}

type FrameAddScriptTagRequest struct {
	Content *string `json:"content,omitempty"`
	Type    *string `json:"type,omitempty"`
	Url     *string `json:"url,omitempty"`
}

type FrameAddScriptTagResponse struct {
	Element ElementHandle `json:"element"`
}

type FrameAddStyleTagRequest struct {
	Content *string `json:"content,omitempty"`
	Url     *string `json:"url,omitempty"`
}

type FrameAddStyleTagResponse struct {
	Element ElementHandle `json:"element"`
}

type FrameAriaSnapshotRequest struct {
	Boxes    *bool   `json:"boxes,omitempty"`
	Depth    *int    `json:"depth,omitempty"`
	Mode     any     `json:"mode"`
	Selector *string `json:"selector,omitempty"`
}

type FrameAriaSnapshotResponse struct {
	Snapshot string `json:"snapshot"`
}

type FrameAriaSnapshotJSONRequest struct {
	Boxes    *bool   `json:"boxes,omitempty"`
	Depth    *int    `json:"depth,omitempty"`
	Mode     any     `json:"mode"`
	Selector *string `json:"selector,omitempty"`
}

type FrameAriaSnapshotJSONResponse struct {
	Snapshot any `json:"snapshot"`
}

type FrameBlurRequest struct {
	Selector string `json:"selector"`
	Strict   *bool  `json:"strict,omitempty"`
}

type FrameBlurResponse struct {
}

type FrameCheckRequest struct {
	Force    *bool  `json:"force,omitempty"`
	Position *Point `json:"position,omitempty"`
	Scroll   any    `json:"scroll"`
	Selector string `json:"selector"`
	Strict   *bool  `json:"strict,omitempty"`
	Trial    *bool  `json:"trial,omitempty"`
}

type FrameCheckResponse struct {
}

type FrameClickRequest struct {
	Button      any      `json:"button"`
	ClickCount  *int     `json:"clickCount,omitempty"`
	Delay       *float64 `json:"delay,omitempty"`
	Force       *bool    `json:"force,omitempty"`
	Modifiers   []any    `json:"modifiers"`
	NoWaitAfter *bool    `json:"noWaitAfter,omitempty"`
	Position    *Point   `json:"position,omitempty"`
	Scroll      any      `json:"scroll"`
	Selector    string   `json:"selector"`
	Steps       *int     `json:"steps,omitempty"`
	Strict      *bool    `json:"strict,omitempty"`
	Trial       *bool    `json:"trial,omitempty"`
}

type FrameClickResponse struct {
}

type FrameContentRequest struct {
}

type FrameContentResponse struct {
	Value string `json:"value"`
}

type FrameDblclickRequest struct {
	Button    any      `json:"button"`
	Delay     *float64 `json:"delay,omitempty"`
	Force     *bool    `json:"force,omitempty"`
	Modifiers []any    `json:"modifiers"`
	Position  *Point   `json:"position,omitempty"`
	Scroll    any      `json:"scroll"`
	Selector  string   `json:"selector"`
	Steps     *int     `json:"steps,omitempty"`
	Strict    *bool    `json:"strict,omitempty"`
	Trial     *bool    `json:"trial,omitempty"`
}

type FrameDblclickResponse struct {
}

type FrameDispatchEventRequest struct {
	EventInit SerializedArgument `json:"eventInit"`
	Selector  string             `json:"selector"`
	Strict    *bool              `json:"strict,omitempty"`
	Type      string             `json:"type"`
}

type FrameDispatchEventResponse struct {
}

type FrameDragAndDropRequest struct {
	Force          *bool  `json:"force,omitempty"`
	Scroll         any    `json:"scroll"`
	Source         string `json:"source"`
	SourcePosition *Point `json:"sourcePosition,omitempty"`
	Steps          *int   `json:"steps,omitempty"`
	Strict         *bool  `json:"strict,omitempty"`
	Target         string `json:"target"`
	TargetPosition *Point `json:"targetPosition,omitempty"`
	Trial          *bool  `json:"trial,omitempty"`
}

type FrameDragAndDropResponse struct {
}

type FrameDropRequest struct {
	Data       []any            `json:"data"`
	LocalPaths []string         `json:"localPaths"`
	Payloads   []any            `json:"payloads"`
	Position   *Point           `json:"position,omitempty"`
	Selector   string           `json:"selector"`
	Streams    []WritableStream `json:"streams"`
	Strict     *bool            `json:"strict,omitempty"`
}

type FrameDropResponse struct {
}

type FrameEvalOnSelectorRequest struct {
	Arg        SerializedArgument `json:"arg"`
	Expression string             `json:"expression"`
	IsFunction *bool              `json:"isFunction,omitempty"`
	Selector   string             `json:"selector"`
	Strict     *bool              `json:"strict,omitempty"`
}

type FrameEvalOnSelectorResponse struct {
	Value SerializedValue `json:"value"`
}

type FrameEvalOnSelectorAllRequest struct {
	Arg        SerializedArgument `json:"arg"`
	Expression string             `json:"expression"`
	IsFunction *bool              `json:"isFunction,omitempty"`
	Selector   string             `json:"selector"`
}

type FrameEvalOnSelectorAllResponse struct {
	Value SerializedValue `json:"value"`
}

type FrameEvaluateExpressionRequest struct {
	Arg        SerializedArgument `json:"arg"`
	Expression string             `json:"expression"`
	IsFunction *bool              `json:"isFunction,omitempty"`
}

type FrameEvaluateExpressionResponse struct {
	Value SerializedValue `json:"value"`
}

type FrameEvaluateExpressionHandleRequest struct {
	Arg        SerializedArgument `json:"arg"`
	Expression string             `json:"expression"`
	IsFunction *bool              `json:"isFunction,omitempty"`
}

type FrameEvaluateExpressionHandleResponse struct {
	Handle JSHandle `json:"handle"`
}

type FrameExpectRequest struct {
	ExpectedNumber *float64            `json:"expectedNumber,omitempty"`
	ExpectedText   []ExpectedTextValue `json:"expectedText"`
	ExpectedValue  *SerializedArgument `json:"expectedValue,omitempty"`
	Expression     string              `json:"expression"`
	ExpressionArg  any                 `json:"expressionArg,omitempty"`
	IsNot          bool                `json:"isNot"`
	Pseudo         any                 `json:"pseudo"`
	Selector       *string             `json:"selector,omitempty"`
	UseInnerText   *bool               `json:"useInnerText,omitempty"`
}

type FrameExpectResponse struct {
}

type FrameFillRequest struct {
	Force    *bool  `json:"force,omitempty"`
	Selector string `json:"selector"`
	Strict   *bool  `json:"strict,omitempty"`
	Value    string `json:"value"`
}

type FrameFillResponse struct {
}

type FrameFocusRequest struct {
	Selector string `json:"selector"`
	Strict   *bool  `json:"strict,omitempty"`
}

type FrameFocusResponse struct {
}

type FrameFrameElementRequest struct {
}

type FrameFrameElementResponse struct {
	Element ElementHandle `json:"element"`
}

type FrameGetAttributeRequest struct {
	Name     string `json:"name"`
	Selector string `json:"selector"`
	Strict   *bool  `json:"strict,omitempty"`
}

type FrameGetAttributeResponse struct {
	Value *string `json:"value,omitempty"`
}

type FrameGotoRequest struct {
	Referer   *string         `json:"referer,omitempty"`
	Url       string          `json:"url"`
	WaitUntil *LifecycleEvent `json:"waitUntil,omitempty"`
}

type FrameGotoResponse struct {
	Response *Response `json:"response,omitempty"`
}

type FrameHideHighlightRequest struct {
	Selector string `json:"selector"`
}

type FrameHideHighlightResponse struct {
}

type FrameHighlightRequest struct {
	Selector string  `json:"selector"`
	Style    *string `json:"style,omitempty"`
}

type FrameHighlightResponse struct {
}

type FrameHoverRequest struct {
	Force     *bool  `json:"force,omitempty"`
	Modifiers []any  `json:"modifiers"`
	Position  *Point `json:"position,omitempty"`
	Scroll    any    `json:"scroll"`
	Selector  string `json:"selector"`
	Strict    *bool  `json:"strict,omitempty"`
	Trial     *bool  `json:"trial,omitempty"`
}

type FrameHoverResponse struct {
}

type FrameInnerHTMLRequest struct {
	Selector string `json:"selector"`
	Strict   *bool  `json:"strict,omitempty"`
}

type FrameInnerHTMLResponse struct {
	Value string `json:"value"`
}

type FrameInnerTextRequest struct {
	Selector string `json:"selector"`
	Strict   *bool  `json:"strict,omitempty"`
}

type FrameInnerTextResponse struct {
	Value string `json:"value"`
}

type FrameInputValueRequest struct {
	Selector string `json:"selector"`
	Strict   *bool  `json:"strict,omitempty"`
}

type FrameInputValueResponse struct {
	Value string `json:"value"`
}

type FrameIsCheckedRequest struct {
	Selector string `json:"selector"`
	Strict   *bool  `json:"strict,omitempty"`
}

type FrameIsCheckedResponse struct {
	Value bool `json:"value"`
}

type FrameIsDisabledRequest struct {
	Selector string `json:"selector"`
	Strict   *bool  `json:"strict,omitempty"`
}

type FrameIsDisabledResponse struct {
	Value bool `json:"value"`
}

type FrameIsEditableRequest struct {
	Selector string `json:"selector"`
	Strict   *bool  `json:"strict,omitempty"`
}

type FrameIsEditableResponse struct {
	Value bool `json:"value"`
}

type FrameIsEnabledRequest struct {
	Selector string `json:"selector"`
	Strict   *bool  `json:"strict,omitempty"`
}

type FrameIsEnabledResponse struct {
	Value bool `json:"value"`
}

type FrameIsHiddenRequest struct {
	Selector string `json:"selector"`
	Strict   *bool  `json:"strict,omitempty"`
}

type FrameIsHiddenResponse struct {
	Value bool `json:"value"`
}

type FrameIsVisibleRequest struct {
	Selector string `json:"selector"`
	Strict   *bool  `json:"strict,omitempty"`
}

type FrameIsVisibleResponse struct {
	Value bool `json:"value"`
}

type FramePressRequest struct {
	Delay       *float64 `json:"delay,omitempty"`
	Key         string   `json:"key"`
	NoWaitAfter *bool    `json:"noWaitAfter,omitempty"`
	Selector    string   `json:"selector"`
	Strict      *bool    `json:"strict,omitempty"`
}

type FramePressResponse struct {
}

type FrameQueryCountRequest struct {
	Selector string `json:"selector"`
}

type FrameQueryCountResponse struct {
	Value int `json:"value"`
}

type FrameQuerySelectorRequest struct {
	Selector string `json:"selector"`
	Strict   *bool  `json:"strict,omitempty"`
}

type FrameQuerySelectorResponse struct {
	Element *ElementHandle `json:"element,omitempty"`
}

type FrameQuerySelectorAllRequest struct {
	Selector string `json:"selector"`
}

type FrameQuerySelectorAllResponse struct {
	Elements []ElementHandle `json:"elements"`
}

type FrameResolveSelectorRequest struct {
	Selector string `json:"selector"`
}

type FrameResolveSelectorResponse struct {
	ResolvedSelector string `json:"resolvedSelector"`
}

type FrameSelectOptionRequest struct {
	Elements []ElementHandle `json:"elements"`
	Force    *bool           `json:"force,omitempty"`
	Options  []any           `json:"options"`
	Selector string          `json:"selector"`
	Strict   *bool           `json:"strict,omitempty"`
}

type FrameSelectOptionResponse struct {
	Values []string `json:"values"`
}

type FrameSetContentRequest struct {
	Html      string          `json:"html"`
	WaitUntil *LifecycleEvent `json:"waitUntil,omitempty"`
}

type FrameSetContentResponse struct {
}

type FrameSetInputFilesRequest struct {
	DirectoryStream *WritableStream  `json:"directoryStream,omitempty"`
	LocalDirectory  *string          `json:"localDirectory,omitempty"`
	LocalPaths      []string         `json:"localPaths"`
	Payloads        []any            `json:"payloads"`
	Selector        string           `json:"selector"`
	Streams         []WritableStream `json:"streams"`
	Strict          *bool            `json:"strict,omitempty"`
}

type FrameSetInputFilesResponse struct {
}

type FrameTapRequest struct {
	Force     *bool  `json:"force,omitempty"`
	Modifiers []any  `json:"modifiers"`
	Position  *Point `json:"position,omitempty"`
	Scroll    any    `json:"scroll"`
	Selector  string `json:"selector"`
	Strict    *bool  `json:"strict,omitempty"`
	Trial     *bool  `json:"trial,omitempty"`
}

type FrameTapResponse struct {
}

type FrameTextContentRequest struct {
	Selector string `json:"selector"`
	Strict   *bool  `json:"strict,omitempty"`
}

type FrameTextContentResponse struct {
	Value *string `json:"value,omitempty"`
}

type FrameTitleRequest struct {
}

type FrameTitleResponse struct {
	Value string `json:"value"`
}

type FrameTypeRequest struct {
	Delay    *float64 `json:"delay,omitempty"`
	Selector string   `json:"selector"`
	Strict   *bool    `json:"strict,omitempty"`
	Text     string   `json:"text"`
}

type FrameTypeResponse struct {
}

type FrameUncheckRequest struct {
	Force    *bool  `json:"force,omitempty"`
	Position *Point `json:"position,omitempty"`
	Scroll   any    `json:"scroll"`
	Selector string `json:"selector"`
	Strict   *bool  `json:"strict,omitempty"`
	Trial    *bool  `json:"trial,omitempty"`
}

type FrameUncheckResponse struct {
}

type FrameWaitForFunctionRequest struct {
	Arg             SerializedArgument `json:"arg"`
	Expression      string             `json:"expression"`
	IsFunction      *bool              `json:"isFunction,omitempty"`
	PollingInterval *float64           `json:"pollingInterval,omitempty"`
	Selector        *string            `json:"selector,omitempty"`
	Strict          *bool              `json:"strict,omitempty"`
}

type FrameWaitForFunctionResponse struct {
	Handle *JSHandle `json:"handle,omitempty"`
}

type FrameWaitForSelectorRequest struct {
	OmitReturnValue *bool  `json:"omitReturnValue,omitempty"`
	Selector        string `json:"selector"`
	State           any    `json:"state"`
	Strict          *bool  `json:"strict,omitempty"`
}

type FrameWaitForSelectorResponse struct {
	Element *ElementHandle `json:"element,omitempty"`
}

type FrameWaitForTimeoutRequest struct {
	WaitTimeout float64 `json:"waitTimeout"`
}

type FrameWaitForTimeoutResponse struct {
}

type FrameLoadstateEvent struct {
	Add    *LifecycleEvent `json:"add,omitempty"`
	Remove *LifecycleEvent `json:"remove,omitempty"`
}

type FrameNavigatedEvent struct {
	Error       *string `json:"error,omitempty"`
	Name        string  `json:"name"`
	NewDocument any     `json:"newDocument"`
	Url         string  `json:"url"`
}

type HttpCredentials struct {
	Origin   *string `json:"origin,omitempty"`
	Password string  `json:"password"`
	Send     any     `json:"send"`
	Username string  `json:"username"`
}

type IndexedDBDatabase struct {
	Name    string `json:"name"`
	Stores  []any  `json:"stores"`
	Version int    `json:"version"`
}

type JSHandle struct {
	Guid string `json:"guid"`
}

type JSHandleDisposeRequest struct {
}

type JSHandleDisposeResponse struct {
}

type JSHandleEvaluateExpressionRequest struct {
	Arg        SerializedArgument `json:"arg"`
	Expression string             `json:"expression"`
	IsFunction *bool              `json:"isFunction,omitempty"`
}

type JSHandleEvaluateExpressionResponse struct {
	Value SerializedValue `json:"value"`
}

type JSHandleEvaluateExpressionHandleRequest struct {
	Arg        SerializedArgument `json:"arg"`
	Expression string             `json:"expression"`
	IsFunction *bool              `json:"isFunction,omitempty"`
}

type JSHandleEvaluateExpressionHandleResponse struct {
	Handle JSHandle `json:"handle"`
}

type JSHandleGetPropertyRequest struct {
	Name string `json:"name"`
}

type JSHandleGetPropertyResponse struct {
	Handle JSHandle `json:"handle"`
}

type JSHandleGetPropertyListRequest struct {
}

type JSHandleGetPropertyListResponse struct {
	Properties []any `json:"properties"`
}

type JSHandleJsonValueRequest struct {
}

type JSHandleJsonValueResponse struct {
	Value SerializedValue `json:"value"`
}

type JSHandlePreviewUpdatedEvent struct {
	Preview string `json:"preview"`
}

type JsonPipe struct {
	Guid string `json:"guid"`
}

type JsonPipeCloseRequest struct {
}

type JsonPipeCloseResponse struct {
}

type JsonPipeSendRequest struct {
	Message any `json:"message"`
}

type JsonPipeSendResponse struct {
}

type JsonPipeClosedEvent struct {
	Reason *string `json:"reason,omitempty"`
}

type JsonPipeMessageEvent struct {
	Message any `json:"message"`
}

type LifecycleEvent string

const (
	LifecycleEventLoad             LifecycleEvent = "load"
	LifecycleEventDomcontentloaded LifecycleEvent = "domcontentloaded"
	LifecycleEventNetworkidle      LifecycleEvent = "networkidle"
	LifecycleEventCommit           LifecycleEvent = "commit"
)

type LocalUtils struct {
	Guid string `json:"guid"`
}

type LocalUtilsAddStackToTracingNoReplyRequest struct {
	CallData ClientSideCallMetadata `json:"callData"`
}

type LocalUtilsAddStackToTracingNoReplyResponse struct {
}

type LocalUtilsConnectRequest struct {
	Endpoint                      string   `json:"endpoint"`
	ExposeNetwork                 *string  `json:"exposeNetwork,omitempty"`
	Headers                       any      `json:"headers,omitempty"`
	SlowMo                        *float64 `json:"slowMo,omitempty"`
	SocksProxyRedirectPortForTest *int     `json:"socksProxyRedirectPortForTest,omitempty"`
}

type LocalUtilsConnectResponse struct {
	Headers []NameValue `json:"headers"`
	Pipe    JsonPipe    `json:"pipe"`
}

type LocalUtilsGlobToRegexRequest struct {
	BaseURL      *string `json:"baseURL,omitempty"`
	Glob         string  `json:"glob"`
	WebSocketUrl *bool   `json:"webSocketUrl,omitempty"`
}

type LocalUtilsGlobToRegexResponse struct {
	Regex string `json:"regex"`
}

type LocalUtilsHarCloseRequest struct {
	HarId string `json:"harId"`
}

type LocalUtilsHarCloseResponse struct {
}

type LocalUtilsHarLookupRequest struct {
	HarId               string      `json:"harId"`
	Headers             []NameValue `json:"headers"`
	IsNavigationRequest bool        `json:"isNavigationRequest"`
	Method              string      `json:"method"`
	PostData            []byte      `json:"postData,omitempty"`
	Url                 string      `json:"url"`
}

type LocalUtilsHarLookupResponse struct {
	Action      any         `json:"action"`
	Body        []byte      `json:"body,omitempty"`
	Headers     []NameValue `json:"headers"`
	Message     *string     `json:"message,omitempty"`
	RedirectURL *string     `json:"redirectURL,omitempty"`
	Status      *int        `json:"status,omitempty"`
}

type LocalUtilsHarOpenRequest struct {
	File string `json:"file"`
}

type LocalUtilsHarOpenResponse struct {
	Error *string `json:"error,omitempty"`
	HarId *string `json:"harId,omitempty"`
}

type LocalUtilsHarUnzipRequest struct {
	HarFile      string  `json:"harFile"`
	ResourcesDir *string `json:"resourcesDir,omitempty"`
	ZipFile      string  `json:"zipFile"`
}

type LocalUtilsHarUnzipResponse struct {
}

type LocalUtilsTraceDiscardedRequest struct {
	StacksId string `json:"stacksId"`
}

type LocalUtilsTraceDiscardedResponse struct {
}

type LocalUtilsTracingStartedRequest struct {
	Live      *bool   `json:"live,omitempty"`
	TraceName string  `json:"traceName"`
	TracesDir *string `json:"tracesDir,omitempty"`
}

type LocalUtilsTracingStartedResponse struct {
	StacksId string `json:"stacksId"`
}

type LocalUtilsZipRequest struct {
	AdditionalSources []string    `json:"additionalSources"`
	Entries           []NameValue `json:"entries"`
	IncludeSources    bool        `json:"includeSources"`
	Mode              any         `json:"mode"`
	StacksId          *string     `json:"stacksId,omitempty"`
	ZipFile           string      `json:"zipFile"`
}

type LocalUtilsZipResponse struct {
}

type Metadata struct {
	Internal *bool    `json:"internal,omitempty"`
	Location any      `json:"location"`
	StepId   *string  `json:"stepId,omitempty"`
	Timeout  *float64 `json:"timeout,omitempty"`
	Title    *string  `json:"title,omitempty"`
}

type NameValue struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type NetworkCookie struct {
	CrHasCrossSiteAncestor *bool   `json:"_crHasCrossSiteAncestor,omitempty"`
	Domain                 string  `json:"domain"`
	Expires                float64 `json:"expires"`
	HttpOnly               bool    `json:"httpOnly"`
	Name                   string  `json:"name"`
	PartitionKey           *string `json:"partitionKey,omitempty"`
	Path                   string  `json:"path"`
	SameSite               any     `json:"sameSite"`
	Secure                 bool    `json:"secure"`
	Value                  string  `json:"value"`
}

type OriginStorage struct {
	IndexedDB    []IndexedDBDatabase `json:"indexedDB"`
	LocalStorage []NameValue         `json:"localStorage"`
	Origin       string              `json:"origin"`
}

type Page struct {
	Guid string `json:"guid"`
}

type PageAddInitScriptRequest struct {
	Source string `json:"source"`
}

type PageAddInitScriptResponse struct {
	Disposable Disposable `json:"disposable"`
}

type PageBringToFrontRequest struct {
}

type PageBringToFrontResponse struct {
}

type PageCancelPickLocatorRequest struct {
}

type PageCancelPickLocatorResponse struct {
}

type PageClearConsoleMessagesRequest struct {
}

type PageClearConsoleMessagesResponse struct {
}

type PageClearPageErrorsRequest struct {
}

type PageClearPageErrorsResponse struct {
}

type PageCloseRequest struct {
	Reason *string `json:"reason,omitempty"`
}

type PageCloseResponse struct {
}

type PageConsoleMessagesRequest struct {
	Filter *ConsoleMessagesFilter `json:"filter,omitempty"`
}

type PageConsoleMessagesResponse struct {
	Messages []any `json:"messages"`
}

type PageEmulateMediaRequest struct {
	ColorScheme   any `json:"colorScheme"`
	Contrast      any `json:"contrast"`
	ForcedColors  any `json:"forcedColors"`
	Media         any `json:"media"`
	ReducedMotion any `json:"reducedMotion"`
}

type PageEmulateMediaResponse struct {
}

type PageExpectScreenshotRequest struct {
	Mixin             any      `json:"$mixin"`
	Clip              *Rect    `json:"clip,omitempty"`
	Comparator        *string  `json:"comparator,omitempty"`
	Expected          []byte   `json:"expected,omitempty"`
	FullPage          *bool    `json:"fullPage,omitempty"`
	IsNot             bool     `json:"isNot"`
	Locator           any      `json:"locator"`
	MaxDiffPixelRatio *float64 `json:"maxDiffPixelRatio,omitempty"`
	MaxDiffPixels     *int     `json:"maxDiffPixels,omitempty"`
	Threshold         *float64 `json:"threshold,omitempty"`
	Type              any      `json:"type"`
}

type PageExpectScreenshotResponse struct {
	Actual []byte `json:"actual,omitempty"`
}

type PageExposeBindingRequest struct {
	Name     string `json:"name"`
	NoGlobal *bool  `json:"noGlobal,omitempty"`
}

type PageExposeBindingResponse struct {
	Disposable Disposable `json:"disposable"`
}

type PageGoBackRequest struct {
	WaitUntil *LifecycleEvent `json:"waitUntil,omitempty"`
}

type PageGoBackResponse struct {
	Response *Response `json:"response,omitempty"`
}

type PageGoForwardRequest struct {
	WaitUntil *LifecycleEvent `json:"waitUntil,omitempty"`
}

type PageGoForwardResponse struct {
	Response *Response `json:"response,omitempty"`
}

type PageHideHighlightRequest struct {
}

type PageHideHighlightResponse struct {
}

type PageKeyboardDownRequest struct {
	Key string `json:"key"`
}

type PageKeyboardDownResponse struct {
}

type PageKeyboardInsertTextRequest struct {
	Text string `json:"text"`
}

type PageKeyboardInsertTextResponse struct {
}

type PageKeyboardPressRequest struct {
	Delay *float64 `json:"delay,omitempty"`
	Key   string   `json:"key"`
}

type PageKeyboardPressResponse struct {
}

type PageKeyboardTypeRequest struct {
	Delay *float64 `json:"delay,omitempty"`
	Text  string   `json:"text"`
}

type PageKeyboardTypeResponse struct {
}

type PageKeyboardUpRequest struct {
	Key string `json:"key"`
}

type PageKeyboardUpResponse struct {
}

type PageMouseClickRequest struct {
	Button     any      `json:"button"`
	ClickCount *int     `json:"clickCount,omitempty"`
	Delay      *float64 `json:"delay,omitempty"`
	X          float64  `json:"x"`
	Y          float64  `json:"y"`
}

type PageMouseClickResponse struct {
}

type PageMouseDownRequest struct {
	Button     any  `json:"button"`
	ClickCount *int `json:"clickCount,omitempty"`
}

type PageMouseDownResponse struct {
}

type PageMouseMoveRequest struct {
	Steps *int    `json:"steps,omitempty"`
	X     float64 `json:"x"`
	Y     float64 `json:"y"`
}

type PageMouseMoveResponse struct {
}

type PageMouseUpRequest struct {
	Button     any  `json:"button"`
	ClickCount *int `json:"clickCount,omitempty"`
}

type PageMouseUpResponse struct {
}

type PageMouseWheelRequest struct {
	DeltaX float64 `json:"deltaX"`
	DeltaY float64 `json:"deltaY"`
}

type PageMouseWheelResponse struct {
}

type PageOpenerRequest struct {
}

type PageOpenerResponse struct {
	Page *Page `json:"page,omitempty"`
}

type PagePageErrorsRequest struct {
	Filter *ConsoleMessagesFilter `json:"filter,omitempty"`
}

type PagePageErrorsResponse struct {
	Errors []SerializedError `json:"errors"`
}

type PagePdfRequest struct {
	DisplayHeaderFooter *bool    `json:"displayHeaderFooter,omitempty"`
	FooterTemplate      *string  `json:"footerTemplate,omitempty"`
	Format              *string  `json:"format,omitempty"`
	HeaderTemplate      *string  `json:"headerTemplate,omitempty"`
	Height              *string  `json:"height,omitempty"`
	Landscape           *bool    `json:"landscape,omitempty"`
	Margin              any      `json:"margin"`
	Outline             *bool    `json:"outline,omitempty"`
	PageRanges          *string  `json:"pageRanges,omitempty"`
	PreferCSSPageSize   *bool    `json:"preferCSSPageSize,omitempty"`
	PrintBackground     *bool    `json:"printBackground,omitempty"`
	Scale               *float64 `json:"scale,omitempty"`
	Tagged              *bool    `json:"tagged,omitempty"`
	Width               *string  `json:"width,omitempty"`
}

type PagePdfResponse struct {
	Pdf []byte `json:"pdf"`
}

type PagePickLocatorRequest struct {
}

type PagePickLocatorResponse struct {
	Selector string `json:"selector"`
}

type PageRegisterLocatorHandlerRequest struct {
	NoWaitAfter *bool  `json:"noWaitAfter,omitempty"`
	Selector    string `json:"selector"`
}

type PageRegisterLocatorHandlerResponse struct {
	Uid int `json:"uid"`
}

type PageReloadRequest struct {
	WaitUntil *LifecycleEvent `json:"waitUntil,omitempty"`
}

type PageReloadResponse struct {
	Response *Response `json:"response,omitempty"`
}

type PageRequestGCRequest struct {
}

type PageRequestGCResponse struct {
}

type PageRequestsRequest struct {
}

type PageRequestsResponse struct {
	Requests []Request `json:"requests"`
}

type PageResolveLocatorHandlerNoReplyRequest struct {
	Remove *bool `json:"remove,omitempty"`
	Uid    int   `json:"uid"`
}

type PageResolveLocatorHandlerNoReplyResponse struct {
}

type PageRunBeforeUnloadRequest struct {
}

type PageRunBeforeUnloadResponse struct {
}

type PageScreencastChapterRequest struct {
	Description *string  `json:"description,omitempty"`
	Duration    *float64 `json:"duration,omitempty"`
	Title       string   `json:"title"`
}

type PageScreencastChapterResponse struct {
}

type PageScreencastFrameAckRequest struct {
	FrameId int `json:"frameId"`
}

type PageScreencastFrameAckResponse struct {
}

type PageScreencastHideActionsRequest struct {
}

type PageScreencastHideActionsResponse struct {
}

type PageScreencastRemoveOverlayRequest struct {
	Id string `json:"id"`
}

type PageScreencastRemoveOverlayResponse struct {
}

type PageScreencastSetOverlayVisibleRequest struct {
	Visible bool `json:"visible"`
}

type PageScreencastSetOverlayVisibleResponse struct {
}

type PageScreencastShowActionsRequest struct {
	Mixin any `json:"$mixin"`
}

type PageScreencastShowActionsResponse struct {
}

type PageScreencastShowOverlayRequest struct {
	Duration *float64 `json:"duration,omitempty"`
	Html     string   `json:"html"`
}

type PageScreencastShowOverlayResponse struct {
	Id string `json:"id"`
}

type PageScreencastStartRequest struct {
	Quality    *int  `json:"quality,omitempty"`
	Record     *bool `json:"record,omitempty"`
	SendFrames *bool `json:"sendFrames,omitempty"`
	Size       any   `json:"size"`
}

type PageScreencastStartResponse struct {
	Artifact *Artifact `json:"artifact,omitempty"`
}

type PageScreencastStopRequest struct {
}

type PageScreencastStopResponse struct {
}

type PageScreenshotRequest struct {
	Mixin    any   `json:"$mixin"`
	Clip     *Rect `json:"clip,omitempty"`
	FullPage *bool `json:"fullPage,omitempty"`
	Quality  *int  `json:"quality,omitempty"`
	Type     any   `json:"type"`
}

type PageScreenshotResponse struct {
	Binary []byte `json:"binary"`
}

type PageSetDockTileRequest struct {
	Image []byte `json:"image"`
}

type PageSetDockTileResponse struct {
}

type PageSetExtraHTTPHeadersRequest struct {
	Headers []NameValue `json:"headers"`
}

type PageSetExtraHTTPHeadersResponse struct {
}

type PageSetNetworkInterceptionPatternsRequest struct {
	Patterns []any `json:"patterns"`
}

type PageSetNetworkInterceptionPatternsResponse struct {
}

type PageSetViewportSizeRequest struct {
	ViewportSize any `json:"viewportSize"`
}

type PageSetViewportSizeResponse struct {
}

type PageSetWebSocketInterceptionPatternsRequest struct {
	Patterns []any `json:"patterns"`
}

type PageSetWebSocketInterceptionPatternsResponse struct {
}

type PageStartCSSCoverageRequest struct {
	ResetOnNavigation *bool `json:"resetOnNavigation,omitempty"`
}

type PageStartCSSCoverageResponse struct {
}

type PageStartJSCoverageRequest struct {
	ReportAnonymousScripts *bool `json:"reportAnonymousScripts,omitempty"`
	ResetOnNavigation      *bool `json:"resetOnNavigation,omitempty"`
}

type PageStartJSCoverageResponse struct {
}

type PageStopCSSCoverageRequest struct {
}

type PageStopCSSCoverageResponse struct {
	Entries []any `json:"entries"`
}

type PageStopJSCoverageRequest struct {
}

type PageStopJSCoverageResponse struct {
	Entries []any `json:"entries"`
}

type PageTouchscreenTapRequest struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
}

type PageTouchscreenTapResponse struct {
}

type PageUnregisterLocatorHandlerRequest struct {
	Uid int `json:"uid"`
}

type PageUnregisterLocatorHandlerResponse struct {
}

type PageUpdateSubscriptionRequest struct {
	Enabled bool `json:"enabled"`
	Event   any  `json:"event"`
}

type PageUpdateSubscriptionResponse struct {
}

type PageWebStorageClearRequest struct {
	Kind any `json:"kind"`
}

type PageWebStorageClearResponse struct {
}

type PageWebStorageGetItemRequest struct {
	Kind any    `json:"kind"`
	Name string `json:"name"`
}

type PageWebStorageGetItemResponse struct {
	Value *string `json:"value,omitempty"`
}

type PageWebStorageItemsRequest struct {
	Kind any `json:"kind"`
}

type PageWebStorageItemsResponse struct {
	Items []NameValue `json:"items"`
}

type PageWebStorageRemoveItemRequest struct {
	Kind any    `json:"kind"`
	Name string `json:"name"`
}

type PageWebStorageRemoveItemResponse struct {
}

type PageWebStorageSetItemRequest struct {
	Kind  any    `json:"kind"`
	Name  string `json:"name"`
	Value string `json:"value"`
}

type PageWebStorageSetItemResponse struct {
}

type PageBindingCallEvent struct {
	Binding BindingCall `json:"binding"`
}

type PageCloseEvent struct {
}

type PageCrashEvent struct {
}

type PageDownloadEvent struct {
	Artifact          Artifact `json:"artifact"`
	SuggestedFilename string   `json:"suggestedFilename"`
	Url               string   `json:"url"`
}

type PageFileChooserEvent struct {
	Element    ElementHandle `json:"element"`
	IsMultiple bool          `json:"isMultiple"`
}

type PageFrameAttachedEvent struct {
	Frame Frame `json:"frame"`
}

type PageFrameDetachedEvent struct {
	Frame Frame `json:"frame"`
}

type PageLocatorHandlerTriggeredEvent struct {
	Uid int `json:"uid"`
}

type PageRouteEvent struct {
	Route Route `json:"route"`
}

type PageScreencastFrameEvent struct {
	Data           []byte  `json:"data"`
	FrameId        int     `json:"frameId"`
	Timestamp      float64 `json:"timestamp"`
	ViewportHeight int     `json:"viewportHeight"`
	ViewportWidth  int     `json:"viewportWidth"`
}

type PageViewportSizeChangedEvent struct {
	ViewportSize any `json:"viewportSize"`
}

type PageWebSocketEvent struct {
	WebSocket WebSocket `json:"webSocket"`
}

type PageWebSocketRouteEvent struct {
	WebSocketRoute WebSocketRoute `json:"webSocketRoute"`
}

type PageWorkerEvent struct {
	Worker Worker `json:"worker"`
}

type Playwright struct {
	Guid string `json:"guid"`
}

type PlaywrightNewRequestRequest struct {
	BaseURL            *string           `json:"baseURL,omitempty"`
	ClientCertificates []any             `json:"clientCertificates"`
	ExtraHTTPHeaders   []NameValue       `json:"extraHTTPHeaders"`
	FailOnStatusCode   *bool             `json:"failOnStatusCode,omitempty"`
	HttpCredentials    []HttpCredentials `json:"httpCredentials"`
	IgnoreHTTPSErrors  *bool             `json:"ignoreHTTPSErrors,omitempty"`
	MaxRedirects       *int              `json:"maxRedirects,omitempty"`
	Proxy              any               `json:"proxy"`
	StorageState       any               `json:"storageState"`
	TracesDir          *string           `json:"tracesDir,omitempty"`
	UserAgent          *string           `json:"userAgent,omitempty"`
}

type PlaywrightNewRequestResponse struct {
	Request APIRequestContext `json:"request"`
}

type Point struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
}

type RecordHarOptions struct {
	Content        any     `json:"content"`
	HarPath        *string `json:"harPath,omitempty"`
	Mode           any     `json:"mode"`
	ResourcesDir   *string `json:"resourcesDir,omitempty"`
	UrlGlob        *string `json:"urlGlob,omitempty"`
	UrlRegexFlags  *string `json:"urlRegexFlags,omitempty"`
	UrlRegexSource *string `json:"urlRegexSource,omitempty"`
}

type RecorderSource struct {
	Group      *string `json:"group,omitempty"`
	Highlight  []any   `json:"highlight"`
	Id         string  `json:"id"`
	IsRecorded bool    `json:"isRecorded"`
	Label      string  `json:"label"`
	Language   string  `json:"language"`
	RevealLine *int    `json:"revealLine,omitempty"`
	Text       string  `json:"text"`
}

type Rect struct {
	Height float64 `json:"height"`
	Width  float64 `json:"width"`
	X      float64 `json:"x"`
	Y      float64 `json:"y"`
}

type RemoteAddr struct {
	IpAddress string `json:"ipAddress"`
	Port      int    `json:"port"`
}

type Request struct {
	Guid string `json:"guid"`
}

type RequestRawRequestHeadersRequest struct {
}

type RequestRawRequestHeadersResponse struct {
	Headers []NameValue `json:"headers"`
}

type RequestResponseRequest struct {
}

type RequestResponseResponse struct {
	Response *Response `json:"response,omitempty"`
}

type RequestSizes struct {
	RequestBodySize     int `json:"requestBodySize"`
	RequestHeadersSize  int `json:"requestHeadersSize"`
	ResponseBodySize    int `json:"responseBodySize"`
	ResponseHeadersSize int `json:"responseHeadersSize"`
}

type ResourceTiming struct {
	ConnectEnd            float64 `json:"connectEnd"`
	ConnectStart          float64 `json:"connectStart"`
	DomainLookupEnd       float64 `json:"domainLookupEnd"`
	DomainLookupStart     float64 `json:"domainLookupStart"`
	RequestStart          float64 `json:"requestStart"`
	ResponseStart         float64 `json:"responseStart"`
	SecureConnectionStart float64 `json:"secureConnectionStart"`
	StartTime             float64 `json:"startTime"`
}

type Response struct {
	Guid string `json:"guid"`
}

type ResponseBodyRequest struct {
}

type ResponseBodyResponse struct {
	Binary []byte `json:"binary"`
}

type ResponseHttpVersionRequest struct {
}

type ResponseHttpVersionResponse struct {
	Value string `json:"value"`
}

type ResponseRawResponseHeadersRequest struct {
}

type ResponseRawResponseHeadersResponse struct {
	Headers []NameValue `json:"headers"`
}

type ResponseSecurityDetailsRequest struct {
}

type ResponseSecurityDetailsResponse struct {
	Value *SecurityDetails `json:"value,omitempty"`
}

type ResponseServerAddrRequest struct {
}

type ResponseServerAddrResponse struct {
	Value *RemoteAddr `json:"value,omitempty"`
}

type ResponseSizesRequest struct {
}

type ResponseSizesResponse struct {
	Sizes RequestSizes `json:"sizes"`
}

type Root struct {
	Guid string `json:"guid"`
}

type RootInitializeRequest struct {
	SdkLanguage SDKLanguage `json:"sdkLanguage"`
}

type RootInitializeResponse struct {
	Playwright Playwright `json:"playwright"`
}

type Route struct {
	Guid string `json:"guid"`
}

type RouteAbortRequest struct {
	ErrorCode *string `json:"errorCode,omitempty"`
}

type RouteAbortResponse struct {
}

type RouteContinueRequest struct {
	Headers    []NameValue `json:"headers"`
	IsFallback bool        `json:"isFallback"`
	Method     *string     `json:"method,omitempty"`
	PostData   *string     `json:"postData,omitempty"` // base64-encoded; nil = not overridden; &"" = override with empty body
	Url        *string     `json:"url,omitempty"`
}

type RouteContinueResponse struct {
}

type RouteFulfillRequest struct {
	Body             *string     `json:"body,omitempty"`
	FetchResponseUid *string     `json:"fetchResponseUid,omitempty"`
	Headers          []NameValue `json:"headers"`
	IsBase64         *bool       `json:"isBase64,omitempty"`
	Status           *int        `json:"status,omitempty"`
}

type RouteFulfillResponse struct {
}

type RouteRedirectNavigationRequestRequest struct {
	Url string `json:"url"`
}

type RouteRedirectNavigationRequestResponse struct {
}

type SDKLanguage string

const (
	SDKLanguageJavascript SDKLanguage = "javascript"
	SDKLanguagePython     SDKLanguage = "python"
	SDKLanguageJava       SDKLanguage = "java"
	SDKLanguageCsharp     SDKLanguage = "csharp"
)

type SecurityDetails struct {
	Issuer      *string  `json:"issuer,omitempty"`
	Protocol    *string  `json:"protocol,omitempty"`
	SubjectName *string  `json:"subjectName,omitempty"`
	ValidFrom   *float64 `json:"validFrom,omitempty"`
	ValidTo     *float64 `json:"validTo,omitempty"`
}

type SelectorEngine struct {
	ContentScript *bool  `json:"contentScript,omitempty"`
	Name          string `json:"name"`
	Source        string `json:"source"`
}

type SerializedArgument struct {
	Handles []any           `json:"handles"`
	Value   SerializedValue `json:"value"`
}

type SerializedError struct {
	Error any              `json:"error"`
	Value *SerializedValue `json:"value,omitempty"`
}

type SerializedValue struct {
	A   []SerializedValue `json:"a"`
	B   *bool             `json:"b,omitempty"`
	Bi  *string           `json:"bi,omitempty"`
	D   *string           `json:"d,omitempty"`
	E   any               `json:"e"`
	Fn  *string           `json:"fn,omitempty"`
	H   *int              `json:"h,omitempty"`
	Id  *int              `json:"id,omitempty"`
	N   *float64          `json:"n,omitempty"`
	O   []any             `json:"o"`
	R   any               `json:"r"`
	Ref *int              `json:"ref,omitempty"`
	S   *string           `json:"s,omitempty"`
	Ta  any               `json:"ta"`
	U   *string           `json:"u,omitempty"`
	V   any               `json:"v"`
}

type SetNetworkCookie struct {
	CrHasCrossSiteAncestor *bool    `json:"_crHasCrossSiteAncestor,omitempty"`
	Domain                 *string  `json:"domain,omitempty"`
	Expires                *float64 `json:"expires,omitempty"`
	HttpOnly               *bool    `json:"httpOnly,omitempty"`
	Name                   string   `json:"name"`
	PartitionKey           *string  `json:"partitionKey,omitempty"`
	Path                   *string  `json:"path,omitempty"`
	SameSite               any      `json:"sameSite"`
	Secure                 *bool    `json:"secure,omitempty"`
	Url                    *string  `json:"url,omitempty"`
	Value                  string   `json:"value"`
}

type SetOriginStorage struct {
	IndexedDB    []IndexedDBDatabase `json:"indexedDB"`
	LocalStorage []NameValue         `json:"localStorage"`
	Origin       string              `json:"origin"`
}

type SocksSupport struct {
	Guid string `json:"guid"`
}

type SocksSupportSocksConnectedRequest struct {
	Host string `json:"host"`
	Port int    `json:"port"`
	Uid  string `json:"uid"`
}

type SocksSupportSocksConnectedResponse struct {
}

type SocksSupportSocksDataRequest struct {
	Data []byte `json:"data"`
	Uid  string `json:"uid"`
}

type SocksSupportSocksDataResponse struct {
}

type SocksSupportSocksEndRequest struct {
	Uid string `json:"uid"`
}

type SocksSupportSocksEndResponse struct {
}

type SocksSupportSocksErrorRequest struct {
	Error string `json:"error"`
	Uid   string `json:"uid"`
}

type SocksSupportSocksErrorResponse struct {
}

type SocksSupportSocksFailedRequest struct {
	ErrorCode string `json:"errorCode"`
	Uid       string `json:"uid"`
}

type SocksSupportSocksFailedResponse struct {
}

type SocksSupportSocksClosedEvent struct {
	Uid string `json:"uid"`
}

type SocksSupportSocksDataEvent struct {
	Data []byte `json:"data"`
	Uid  string `json:"uid"`
}

type SocksSupportSocksRequestedEvent struct {
	Host string `json:"host"`
	Port int    `json:"port"`
	Uid  string `json:"uid"`
}

type StackFrame struct {
	Column   int     `json:"column"`
	File     string  `json:"file"`
	Function *string `json:"function,omitempty"`
	Line     int     `json:"line"`
}

type Stream struct {
	Guid string `json:"guid"`
}

type StreamCloseRequest struct {
}

type StreamCloseResponse struct {
}

type StreamReadRequest struct {
	Size *int `json:"size,omitempty"`
}

type StreamReadResponse struct {
	Binary []byte `json:"binary"`
}

type Tracing struct {
	Guid string `json:"guid"`
}

type TracingHarExportRequest struct {
	HarId *string `json:"harId,omitempty"`
	Mode  any     `json:"mode"`
}

type TracingHarExportResponse struct {
	Artifact *Artifact   `json:"artifact,omitempty"`
	Entries  []NameValue `json:"entries"`
}

type TracingHarStartRequest struct {
	Options RecordHarOptions `json:"options"`
	Page    *Page            `json:"page,omitempty"`
}

type TracingHarStartResponse struct {
	HarId string `json:"harId"`
}

type TracingTracingGroupRequest struct {
	Location any    `json:"location"`
	Name     string `json:"name"`
}

type TracingTracingGroupResponse struct {
}

type TracingTracingGroupEndRequest struct {
}

type TracingTracingGroupEndResponse struct {
}

type TracingTracingStartRequest struct {
	Live           *bool   `json:"live,omitempty"`
	Name           *string `json:"name,omitempty"`
	Screencast     *bool   `json:"screencast,omitempty"`
	SnapshotAria   *bool   `json:"snapshotAria,omitempty"`
	SnapshotDom    *bool   `json:"snapshotDom,omitempty"`
	SnapshotScreen *bool   `json:"snapshotScreen,omitempty"`
}

type TracingTracingStartResponse struct {
}

type TracingTracingStartChunkRequest struct {
	Name  *string `json:"name,omitempty"`
	Title *string `json:"title,omitempty"`
}

type TracingTracingStartChunkResponse struct {
	TraceName string `json:"traceName"`
}

type TracingTracingStopRequest struct {
}

type TracingTracingStopResponse struct {
}

type TracingTracingStopChunkRequest struct {
	Mode any `json:"mode"`
}

type TracingTracingStopChunkResponse struct {
	Artifact *Artifact   `json:"artifact,omitempty"`
	Entries  []NameValue `json:"entries"`
}

type URLPattern struct {
	Hash     string `json:"hash"`
	Hostname string `json:"hostname"`
	Password string `json:"password"`
	Pathname string `json:"pathname"`
	Port     string `json:"port"`
	Protocol string `json:"protocol"`
	Search   string `json:"search"`
	Username string `json:"username"`
}

type VirtualCredential struct {
	Id         string `json:"id"`
	PrivateKey string `json:"privateKey"`
	PublicKey  string `json:"publicKey"`
	RpId       string `json:"rpId"`
	UserHandle string `json:"userHandle"`
}

type WaitInfo struct {
	Error   *string `json:"error,omitempty"`
	Event   *string `json:"event,omitempty"`
	Message *string `json:"message,omitempty"`
	Phase   any     `json:"phase"`
	WaitId  string  `json:"waitId"`
}

type WebSocket struct {
	Guid string `json:"guid"`
}

type WebSocketCloseEvent struct {
}

type WebSocketFrameReceivedEvent struct {
	Data   string `json:"data"`
	Opcode int    `json:"opcode"`
}

type WebSocketFrameSentEvent struct {
	Data   string `json:"data"`
	Opcode int    `json:"opcode"`
}

type WebSocketOpenEvent struct {
}

type WebSocketSocketErrorEvent struct {
	Error string `json:"error"`
}

type WebSocketRoute struct {
	Guid string `json:"guid"`
}

type WebSocketRouteClosePageRequest struct {
	Code     *int    `json:"code,omitempty"`
	Reason   *string `json:"reason,omitempty"`
	WasClean bool    `json:"wasClean"`
}

type WebSocketRouteClosePageResponse struct {
}

type WebSocketRouteCloseServerRequest struct {
	Code     *int    `json:"code,omitempty"`
	Reason   *string `json:"reason,omitempty"`
	WasClean bool    `json:"wasClean"`
}

type WebSocketRouteCloseServerResponse struct {
}

type WebSocketRouteConnectRequest struct {
}

type WebSocketRouteConnectResponse struct {
}

type WebSocketRouteEnsureOpenedRequest struct {
}

type WebSocketRouteEnsureOpenedResponse struct {
}

type WebSocketRouteSendToPageRequest struct {
	IsBase64 bool   `json:"isBase64"`
	Message  string `json:"message"`
}

type WebSocketRouteSendToPageResponse struct {
}

type WebSocketRouteSendToServerRequest struct {
	IsBase64 bool   `json:"isBase64"`
	Message  string `json:"message"`
}

type WebSocketRouteSendToServerResponse struct {
}

type WebSocketRouteClosePageEvent struct {
	Code     *int    `json:"code,omitempty"`
	Reason   *string `json:"reason,omitempty"`
	WasClean bool    `json:"wasClean"`
}

type WebSocketRouteCloseServerEvent struct {
	Code     *int    `json:"code,omitempty"`
	Reason   *string `json:"reason,omitempty"`
	WasClean bool    `json:"wasClean"`
}

type WebSocketRouteMessageFromPageEvent struct {
	IsBase64 bool   `json:"isBase64"`
	Message  string `json:"message"`
}

type WebSocketRouteMessageFromServerEvent struct {
	IsBase64 bool   `json:"isBase64"`
	Message  string `json:"message"`
}

type Worker struct {
	Guid string `json:"guid"`
}

type WorkerDisconnectRequest struct {
	Reason *string `json:"reason,omitempty"`
}

type WorkerDisconnectResponse struct {
}

type WorkerEvaluateExpressionRequest struct {
	Arg        SerializedArgument `json:"arg"`
	Expression string             `json:"expression"`
	IsFunction *bool              `json:"isFunction,omitempty"`
}

type WorkerEvaluateExpressionResponse struct {
	Value SerializedValue `json:"value"`
}

type WorkerEvaluateExpressionHandleRequest struct {
	Arg        SerializedArgument `json:"arg"`
	Expression string             `json:"expression"`
	IsFunction *bool              `json:"isFunction,omitempty"`
}

type WorkerEvaluateExpressionHandleResponse struct {
	Handle JSHandle `json:"handle"`
}

type WorkerUpdateSubscriptionRequest struct {
	Enabled bool `json:"enabled"`
	Event   any  `json:"event"`
}

type WorkerUpdateSubscriptionResponse struct {
}

type WorkerCloseEvent struct {
}

type WorkerConsoleEvent struct {
	Mixin any `json:"$mixin"`
}

type WritableStream struct {
	Guid string `json:"guid"`
}

type WritableStreamCloseRequest struct {
}

type WritableStreamCloseResponse struct {
}

type WritableStreamWriteRequest struct {
	Binary []byte `json:"binary"`
}

type WritableStreamWriteResponse struct {
}
